' This file is used by Code Analysis to maintain SuppressMessage
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="Leave for reference", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.ConvertModTypeToString(ParamFileEditor.IMassTweaker.ModTypes)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0140:Object creation can be simplified", Justification:="Auto-generated code", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.InitializeComponent")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.clsDeconvolveIsoMods.getIsoModValue(System.Char,ParamFileGenerator.clsReconstituteIsoMods.AvailableAtoms,System.Single)~System.Single")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.clsDMSParamUpload.tmpSaveMods(ParamFileGenerator.clsParams@,ParamFileEditor.IMassTweaker@)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmAboutBox.frmAboutBox_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSParamNamer.cmdCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSParamNamer.cmdUpload_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSParamNamer.frmDMSParamNamer_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSParamNamer.txtSaveFileName_TextChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSParamNamer.txtSaveFileName_Validating(System.Object,System.ComponentModel.CancelEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSPicker.cmdLoadParam_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSPicker.cmdSearch_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSPicker.frmDMSPicker_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSPicker.lvwDMSPickList_ColumnClick(System.Object,System.Windows.Forms.ColumnClickEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSPicker.lvwDMSPickList_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSPicker.txtLiveSearch_KeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmDMSPicker.txtLiveSearch_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.cmdAddNew_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.cmdUseSelectedMod_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.frmGlobalModNamer_Closing(System.Object,System.ComponentModel.CancelEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.lvwExistingMods_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.lvwExistingMods_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.txtDescription_Validating(System.Object,System.ComponentModel.CancelEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.txtModMass_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.txtModMass_Validating(System.Object,System.ComponentModel.CancelEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.txtSymbolName_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmGlobalModNamer.txtSymbolName_Validating(System.Object,System.ComponentModel.CancelEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboCleavagePosition_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboEnzymeSelect_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboFragmentMassType_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboFragmentMassUnits_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboMissedCleavages_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboNucReadingFrame_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboParentMassType_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cboParentMassUnits_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkAutoTweak_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkCreateOutputFiles_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkPrintDupRefs_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkRemovePrecursorPeaks_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkResiduesInUpperCase_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkShowFragmentIons_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkUseAIons_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkUseBIons_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.chkUseYIons_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.cmdReTweak_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.frmMainGUI_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuBatchUploadDMS_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuDebugSyncAll_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuDebugSyncDesc_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuDebugSyncSingle_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuFileExit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuFileLoadFromDMS_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuFileSaveBW2_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuFileSaveBW3_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuFileSaveBW32_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuFileUploadDMS_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuHelpAbout_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.mnuLoadFromFile_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.numericTextBox_KeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtAla_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtArg_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtAsn_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtAsp_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtAWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtBWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtCTPep_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtCTProt_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtCWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtCys_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDescription_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynCTPep_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod1List_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod1MassDiff_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod2List_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod2MassDiff_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod3List_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod3MassDiff_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod4List_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod4MassDiff_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod5List_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynMod5MassDiff_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtDynNTPep_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtFragMassTol_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtGln_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtGlu_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtGly_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtHis_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtIle_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtIonCutoff_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtIsoC_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtIsoH_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtIsoN_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtIsoO_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtIsoS_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtLeu_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtLys_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtMatchPeakCount_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtMatchPeakCountErrors_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtMaxAAPerDynMod_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtMaxDiffPerPeptide_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtMaxProtMass_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtMet_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtMinProtMass_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtNandD_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtNTPep_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtNTProt_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtNumDescLines_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtNumOutputLines_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtNumResults_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtOrn_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtPartialSeq_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtPeakMatchingTol_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtPepMassTol_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtPhe_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtPro_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtQandE_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtSer_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtThr_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtTrp_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtTyr_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtVal_Validated(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtVWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtWWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtXWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtYWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~M:ParamFileEditor.frmMainGUI.txtZWeight_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmAboutBox.lblVersionString")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmAboutBox.ttProviderAboutBox")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSParamNamer.cmdCancel")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSParamNamer.cmdUpload")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSParamNamer.lblDiffs")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSParamNamer.lblSaveFileName")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSParamNamer.txtDiffs")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSParamNamer.txtSaveFileName")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSPicker.cmdLoadParam")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSPicker.cmdSearch")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSPicker.colDiffs")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSPicker.colFileName")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSPicker.colParamID")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSPicker.lvwDMSPicklist")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmDMSPicker.txtLiveSearch")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.cmdAddNew")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.cmdUseSelectedMod")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.colDescription")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.colModMass")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.colSymbol")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.errorProvider")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.gbxExistingMods")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.gbxNewMod")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.lblDescription")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.lblMessages")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.lblModMass")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.lblSymbolName")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.lvwExistingMods")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.toolTipProvider")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.txtDescription")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.txtModMass")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmGlobalModNamer.txtSymbolName")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboCleavagePosition")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboEnzymeSelect")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboFragmentMassType")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboFragmentMassUnits")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboMissedCleavages")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboNucReadingFrame")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboParentMassType")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cboParentMassUnits")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkAutoTweak")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkCreateOutputFiles")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkPrintDupRefs")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkRemovePrecursorPeaks")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkResiduesInUpperCase")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkShowFragmentIons")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkUseAIons")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkUseBIons")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.chkUseYIons")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.cmdReTweak")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxDesc")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxDynMods")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxIonWeighting")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxIsoMods")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxMiscParams")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxSearch")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxStaticMods")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxSwitches")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.gbxToleranceValues")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblAla")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblArg")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblAsn")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblAsp")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblAWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblBWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblCleavagePosition")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblCTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblCTProt")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblCWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblCys")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDescription")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynCTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod1List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod1MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod2List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod2MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod3List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod3MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod4List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod4MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod5List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynMod5MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblDynNTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblEnzymeSelect")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblFragMassTol")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblFragmentMassType")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblFragmentMassUnits")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblGln")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblGlu")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblGly")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblHis")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblIle")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblIonCutoff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblIsoC")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblIsoH")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblIsoN")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblIsoO")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblIsoS")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblLeu")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblLorI")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblLys")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblMatchPeakCount")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblMatchPeakCountErrors")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblMaxAAPerDynMod")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblMaxProtMass")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblMet")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblMinProtMass")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblMissedCleavages")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblNandD")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblNTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblNTProt")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblNucReadingFrame")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblNumDescLines")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblNumResults")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblOrn")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblOutputLines")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblParentMassType")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblParentMassUnits")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblPartialSeq")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblPeakMatchingTol")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblPepMassTol")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblPhe")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblPro")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblQandE")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblSeqHdrFilter")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblSer")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblThr")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblTrp")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblTyr")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblVal")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblVWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblWWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblXWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblYWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.lblZWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuBatchUploadDMS")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuDebug")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuDebugSyncAll")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuDebugSyncDesc")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuDebugSyncSingle")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuDiv1")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFile")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFileExit")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFileLoadFromDMS")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFileSaveBW2")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFileSaveBW3")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFileSaveBW32")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFileSaveToFile")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuFileUploadDMS")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuHelp")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuHelpAbout")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuLoadFromFile")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuMain")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.mnuOptionsAutoTweakParams")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.tabAdvanced")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.tabBasic")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.tcMain")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.tooltipProvider")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtAla")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtArg")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtAsn")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtAsp")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtAWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtBWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtCTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtCTProt")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtCWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtCys")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDescription")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynCTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod1List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod1MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod2List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod2MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod3List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod3MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod4List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod4MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod5List")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynMod5MassDiff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtDynNTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtFragMassTol")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtGln")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtGlu")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtGly")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtHis")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtIle")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtIonCutoff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtIsoC")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtIsoH")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtIsoN")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtIsoO")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtIsoS")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtLeu")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtLys")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtMatchPeakCount")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtMatchPeakCountErrors")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtMaxAAPerDynMod")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtMaxDiffPerPeptide")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtMaxProtMass")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtMet")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtMinProtMass")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtNandD")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtNTPep")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtNTProt")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtNumDescLines")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtNumOutputLines")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtNumResults")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtOrn")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtParamInfo")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtPartialSeq")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtPeakMatchingTol")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtPepMassTol")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtPhe")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtPro")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtQandE")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtSer")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtThr")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtTrp")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtTyr")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtVal")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtVWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtWWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtXWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtYWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.frmMainGUI.txtZWeight")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="member", Target:="~P:ParamFileEditor.ProgramSettings.IProgramSettings.templateFileName")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsAccessEmbeddedRsrc")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsBatchLoadTemplates")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsDeconvolveIsoMods")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsDMSParamUpload")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsDMSPickerHandler")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsMassTweaker")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsSecurityStuff")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsSimpleComparer")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.clsTransferParamEntriesToMassModList")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.frmAboutBox")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.frmDMSParamNamer")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.frmDMSPicker")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.frmGlobalModNamer")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.frmMainGUI")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.frmStreamlinedGUI")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.ProgramSettings.clsCommonModDetails")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.ProgramSettings.clsCommonModsCollection")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="Allowed name", Scope:="type", Target:="~T:ParamFileEditor.ProgramSettings.clsSettings")>
